image: ubuntu

stages:
  - build
  - test

before_script:
  - apt update
  - apt install maven -y


build:
  stage: build
  tags:
    - docker-atp
  script:
    - cd task1
    - mvn clean package
  artifacts:
    paths:
      - target/cargoShipping-1.0-SNAPSHOT.jar
    expire_in: 1 hour
  after_script:
    - echo "BUILD PASSED"

test:
  stage: test
  tags:
    - docker-atp
  script:
    - cd task1
    - mvn verify
    - echo "TESTS PASSED"
